Repository cms-gem-daq-project/gemctp7user, pull requests merged in 2018-06, with the labels that each got.

#26 Develop is Behind Master
  scripts/initOHv3b.sh
  scripts/initOHv3b_NoGBTs.sh
  scripts/recover.sh
  scripts/recover_v2.sh
  scripts/recover_v3.sh
  scripts/replace_parameter.sh
  setup_ctp7.sh
Labels: Priority: Medium, Type: Maintenance

#27 Bug Fix: Corrected sca.py and reg_interface.py syntax errors
  scripts/initOHv3b.sh
  scripts/initOHv3b_NoGBTs.sh
Labels: Priority: Medium, Type: Bugfix, Type: Maintenance

#31 Fix #30
  setup_ctp7.sh
Labels: Priority: High, Type: Bugfix
