Repository cms-gem-daq-project/gemctp7user, pull requests merged in 2019-02, with the labels that each got.

#40 New Feature: Program GBTs given an ohMask
  scripts/initGBTs.sh
Labels: PR: reviewed-approved, Priority: Medium

#41 fixed gth config scripts to take into account miniPOD links and fix OH10 link0
  scripts/gth_config_opto.sh
  scripts/gth_config_opto_tx_inverted.sh
Labels: PR: reviewed-approved, Priority: High, Status: In Progress, Type: Bugfix

#43 Bringing a hacky update to accomodate ge21
  setup_ctp7.sh
Labels: PR: reviewed-approved
